---
title: "CI_analyze"
author: "Chenyu Wu"
date: "2022/6/15"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Initialize


```{r}

library(readxl)
library(ggplot2)
library(ggsignif)
set.seed(123)
```

In order to see the effect of different model, we apply:
```{r}
p <- read_excel("C:/Users/euclid/OneDrive/UMN-My-gear/Code/Stochastic_model/Confidence_Interval/CI_width_2022_OCT/p(30).xlsx")
GR1 <- read_excel("C:/Users/euclid/OneDrive/UMN-My-gear/Code/Stochastic_model/Confidence_Interval/CI_width_2022_OCT/GR1(30).xlsx")
GR2 <- read_excel("C:/Users/euclid/OneDrive/UMN-My-gear/Code/Stochastic_model/Confidence_Interval/CI_width_2022_OCT/GR2(30).xlsx")
p$method <- as.factor(rep(c('Phenopop','End-points','Live cell image'), each = 30))
p$CI_width <- p$p_a1
p.method <- lm(CI_width ~ method,data = p)

GR1$CI_width <- GR1$GR1_a1
GR1$method <- as.factor(rep(c('Phenopop','End-points','Live cell image'), each = 30))
GR1.method <- lm(CI_width ~ method,data = GR1)

GR2$CI_width <- GR2$GR2_a1
GR2$method <- as.factor(rep(c('Phenopop','End-points','Live cell image'), each = 30))
GR2.method <- lm(CI_width ~ method,data = GR2)
par(mfrow = c(1,2));plot(p.method,which = c(1,2))
par(mfrow = c(1,2));plot(GR1.method,which = c(1,2))
par(mfrow = c(1,2));plot(GR2.method,which = c(1,2))
```
Then we have anova for p
```{r}
anova(p.method)
```
anova for GR1
```{r}
anova(GR1.method)
```
anova for GR2
```{r}
anova(GR2.method)
```
pairwise for p
```{r}
pairwise(p.method,term = method)
```
pairwise for GR1
```{r}
pairwise(GR1.method,term = method)
```

pairwise for GR2
```{r}
pairwise(GR2.method,term = method)
```

Boxplot for proportion
```{r}
plo.p <- ggplot(p, aes(x=method, y=CI_width)) +
  geom_boxplot(aes(x = method,outlier.shap = NA)) +
  geom_signif(comparisons = list(c("Phenopop", "Live cell image"),
                                 c("Phenopop", "End-points"),
                                 c("End-points", "Live cell image")),
              test = "wilcox.test", step_increase = 0.075,
              map_signif_level = TRUE, tip_length = 0) +
  theme(text = element_text(size = 24))
```
Boxplot for GR1
```{r}
plo.GR1 <- ggplot(GR1, aes(x=method, y=CI_width)) +
  geom_boxplot(aes(x = method,outlier.shap = NA)) +
  geom_signif(comparisons = list(c("Phenopop", "Live cell image"),
                                 c("Phenopop", "End-points"),
                                 c("End-points", "Live cell image")),
              test = "wilcox.test", step_increase = 0.075,
              map_signif_level = TRUE, tip_length = 0) +
  theme(text = element_text(size = 24))
```
Boxplot for GR2
```{r}
plo.GR2 <- ggplot(GR2, aes(x=method, y=CI_width)) +
  geom_boxplot(aes(x = method,outlier.shap = NA)) +
  geom_signif(comparisons = list(c("Phenopop", "Live cell image"),
                                 c("Phenopop", "End-points"),
                                 c("End-points", "Live cell image")),
              test = "wilcox.test", step_increase = 0.075,
              map_signif_level = TRUE, tip_length = 0) +
  theme(text = element_text(size = 24))
```


